---
page-layout: full
format: 
  html:
    theme: quartz
---

# Segmentation (with a basic workflow)

## Data 

Download links to data:

+ [median composite image](https://cpslo-my.sharepoint.com/:i:/g/personal/mthuggin_calpoly_edu/IQC6Qrj_lbP2QqXekQ4w4yQeAXpYURPD6mSP2u-bkB4-Urc?e=9wV35w)
+ [max composite image](https://cpslo-my.sharepoint.com/:i:/g/personal/mthuggin_calpoly_edu/IQAjxciGVyL-R6vO3V0U1HODAQbjdadeuhyOR07YxrA8vZA?e=GqfPgK)


Make a directory for this lab, and the next, called `susques`. Put the data into a data folder.  Open QGIS, start a project. Save it as `susques.qgz`.  (You will answer questions later in `lab_11_answers.txt`)
```
susques/
├── susques.qgz
├── data/
│   ├── s2_susques_max_2025_clipped.tif
│   └── s2_susques_median_2025_clipped.tif
└── lab_11_answers.txt
```

For this project, you have two Sentinel-2 images (from Google Earth Engine's [Harmonized Sentinel-2 MSI Level-2A Surface Reflectance collection](https://developers.google.com/earth-engine/datasets/catalog/COPERNICUS_S2_SR_HARMONIZED)) to work with.  The first is a _median composite image_ and, the second, a _max composite image_. Both images are of the same scene, near [Susques, Argentina](https://en.wikipedia.org/wiki/Susques), In the [Atacama Desert](https://en.wikipedia.org/wiki/Atacama_Desert).  They are taken over the period from 2025-04-01 to 2025-10-26.

The bands available in the two composite images are listed in @tbl-bands. 

## Segmentation using a binary mask 


In this exercise you will segment the image to find the [lithium brine evaporation ponds](https://eros.usgs.gov/earthshots/ponds), using only the raster calculator, and the Polygonize tool (Raster to Vector, from GDAL)

To do this you will need to:

1. Select an appropriate spectral index (or indices) and calculate it using Raster Calculator
2. Create a binary mask (pond / not pond) by using a threshold value of your spectral index. 
3. Calculate the total area of the ponds.
4. Answer these questions in `lab_11_answers.txt`

> q1. What spectral index (or indices) did you use?   
> q2. What bands are involved in the index and why are those bands useful for this task?  
> q3. What was the threshold value used to create you mask?  
> q4. What is the total area of the brine evaporation ponds?  
> q5. What CRS did you use when measuring the area of the brine evaporation ponds?  
> q6. What is the difference in mean SWIR1 (band 11) within and outside of evaporation ponds in the image?  
> q7. What is a median composite image? A maximum composite image?  


::: {style="font-size:0.9em"}
| GeoTIFF band | Band name | Description | Native pixel size |
|---:|---|---|---:|
| 1 | `B1` | Aerosols | 60 m |
| 2 | `B2` | Blue | 10 m |
| 3 | `B3` | Green | 10 m |
| 4 | `B4` | Red | 10 m |
| 5 | `B5` | Red edge 1 | 20 m |
| 6 | `B6` | Red edge 2 | 20 m |
| 7 | `B7` | Red edge 3 | 20 m |
| 8 | `B8` | Near infrared (NIR) | 10 m |
| 9 | `B8A` | Red edge 4 | 20 m |
| 10 | `B9` | Water vapor | 60 m |
| 11 | `B11` | Shortwave infrared 1 (SWIR1) | 20 m |
| 12 | `B12` | Shortwave infrared 2 (SWIR2) | 20 m |
| 13 | `AOT` | Aerosol optical thickness | 10 m |
| 14 | `WVP` | Water vapor pressure | 10 m |
| 15 | `SCL` | Scene classification map | 20 m |
| 16 | `TCI_R` | True color image, red channel | 10 m |
| 17 | `TCI_G` | True color image, green channel | 10 m |
| 18 | `TCI_B` | True color image, blue channel | 10 m |
| 19 | `MSK_CLDPRB` | Cloud probability map | 20 m |
| 20 | `MSK_SNWPRB` | Snow probability map | 10 m |
| 21 | `QA10` | Always empty | 10 m |
| 22 | `QA20` | Always empty | 20 m |
| 23 | `QA60` | Cloud mask | 60 m |
| 24 | `MSK_CLASSI_OPAQUE` | Opaque cloud classification | 60 m |
| 25 | `MSK_CLASSI_CIRRUS` | Cirrus cloud classification | 60 m |
| 26 | `MSK_CLASSI_SNOW_ICE` | Snow/ice classification | 60 m |

: Sentinel-2 bands available in the composite images {#tbl-bands}

:::