---
title: "Syllabus - NR 218 - Introduction to GIS - Winter 2026"
page-layout: full
format: 
  html:
    theme: quartz
---


[Jump to class calendar](#winter-term-calendar-2026)

## Class Details
Building 10 (Erhart Agriculture, a.k.a. part of _Aglish_), Room 204 

Monday: 9:10 - 1:00  
Wednesday: (9:10 - 12:00) 

## Instructor Details
Michael Huggins  
&#9993; [mthuggin@calpoly.edu](mailto:mthuggin@calpoly.edu)  
Office Hours: Mondays 2:30 - 4:30  
Building 72-107 (Plant Conservatory)  

__TA:__ Dillen Corlett

&#9993; [dicorlet@calpoly.edu](mailto:dicorlet@calpoly.edu)

Dillen will host remote office hours, by appointment, during the quarter for those who cannot make my office hours.  Follow this [link to her schedule](https://calendar.app.google/kKshuBDibeA6inss7) to view available times.
    
## Learning Goals
+ How to formulate and answer problems using spatial data  
+ How to create quality maps and graphics
+ Apply skills in remote sensing, GIS, and data science to solve a problem of your own design
+ Understand basic principles of GIS


## Project Assignments
This course centers on a series of 4 projects using different types of GIS data. The projects build on one another and you will learn new skills for each project. Plenty of class time will be spent on project work. Each student should hand in their own projects. See the [calendar](#fall-term-calendar-2025) for due dates.  Late assignments will be deducted 5% per day late. 

## Labs
Not every lab requires you turn in your results. The [calendar](#fall-term-calendar-2025) lists due dates for the labs that need to be turned in.

## Quizzes
Quizzes can happen any time! How many will there be? 1? 10? Who knows? Quizzes cannot be made up unless you are sick, or have an excused absence (sports, clubs etc...).  If you are sick, you need to email me promptly (ideally before class) to let me know.

## Assignment Weight
| Assignment     | Percentage of Grade| Description  |
|----------------|------|----|
| [Project 1](project_1.html)      | 10  |  Mapping  |
| [Project 2](project_2.html)      | 10  |  Vector Data Analysis  |
| [Project 3](project_3.html)      | 10  |  Raster Data Analysis  |
| [Project 4](project_4.html)      | 20  |  Remote Sensing, Image Analysis, and Modeling  |
| Lab exercises  | 30  |  Not all labs have exercises due, see calendar  |
| Quizzes        | 15  |  Quizzes can happen any time! |
| Participation  |  5  |  Will be based on participation and engagement  |  

## Grading

A: ≥ 90%  
B: ≥ 80%  
C: ≥ 70%  
D: ≥ 60%  
F: < 60%  

Note: Grading is not curved.


## Assignment Submission Policy 
Assignments  will be submitted on Canvas.  Late assignments will be penalized by 5% for every day they are late.

## Academic Integrity
All students should be familiar with and adhere to the university’s academic integrity policy, which can be found here: https://osrr.calpoly.edu/academic-integrity 

## Use of AI
AI generated text __may not be used__ for any writing.

Students can seek AI assistance for project work, but it is important to consider that AI will make you stupid ([See this study for example](https://www.researchgate.net/publication/392560878_Your_Brain_on_ChatGPT_Accumulation_of_Cognitive_Debt_when_Using_an_AI_Assistant_for_Essay_Writing_Task)) and waste your time!

  + Depending on AI prevents development of critical thinking, writing, and problem-solving skills
  + AI will often lead you down a terrible, deep rabbit hole of confusion
  + Getting quick answers without working through problems will leave gaps in foundational knowledge needed for advanced coursework
  + The struggle of working through difficult concepts is often where the most valuable learning occurs
  + AI uses heaps of electricity

That is not to say LLMs are never useful or appropriate to use, but you need to know their limitations.  I suggest reading this [critical AI literacy guide](https://rutgers.app.box.com/s/v1ywq3701cb6pvnewz5ptuhojwwppmsg/file/1640499870205) from Rutgers University.

 
## Textbook
You will read excerpts from Essentials of Geographic Information Systems during this course. A free and online version of the textbook can be found [here](https://saylordotorg.github.io/text_essentials-of-geographic-information-systems).


## Tutorials
We will refer to a number of tutorial videos which describe QGIS processing. These will come primarily from two sources: 

[Ujaval Gandhi's QGIS Tutorials and Tips](https://www.qgistutorials.com/en/index.html)  
[QGIS Training Manual](https://docs.qgis.org/3.34/en/docs/training_manual/index.html)

There are many other helpful sources of information on GIS Software, here area couple:

[Spatial Thoughts introduction-to-qgis.html ](https://courses.spatialthoughts.com/)   
[A Gentle Introduction to GIS  gentle_gis_introduction/index.html](https://docs.qgis.org/3.40/en/docs/)



# Winter Term Calendar 2026

| Date         | Week | Lecture                                                              | Lab    | Reading      | Due Dates                                     |
|--------------|------|----------------------------------------------------------------------|--------|--------------|-----------------------------------------------|
| January 5    | 1    | Introduction, Computers                                              | Lab 1  | ch. 1 and 2 as well as [this page about computers](computers.html) | |
| January 7    | 1    | Basic GIS Concepts,  Scale, Coordinate systems, and Map Projections  | Lab 2  |              | [Lab 1](computers_lab.html)                   |
| January 12   | 2    | Spatial Data Models and File Formats                                 | Lab 3  | ch. 3 and 4  |                                               |
| January 14   | 2    |                                                                      | Lab 4  |              |                                               |
| January 20 (Tuesday) | 3 | Review: Coordinate Systems, Map Projections, Datums; Reprojection; GeoProcessing and Vector Operations  | Lab 5 | ch. 5 and 6  | [Project 1](project_1.html)                   |
| January 21   | 3    | GeoProcessing and Vector Operations                                  | Lab 6  |              |                                               |
| January 26   | 4    | Data Creation, Editing, Topology Basics                              | Lab 7  | ch. 7 and 8  |                                               |
| January 28   | 4    | Rasters and Elevation Data                                           | Lab 8  |              |                                               |
| February 2   | 5    | Raster Analysis: Map Algebra, Resampling, Reprojecting Rasters       | Lab 9  | ch. 9 and 10 | [Project 2](project_2.html)                   |
| February 4   | 5    | Remote Sensing and Spectral Indices                                  | Lab 10 |              | [Lab 8](lab_8.html)                           |
| February 9   | 6    | Segmentation                                                         | Lab 11 |              |                                               |
| February 11  | 6    | Raster $\times$ Vector Operations, Zonal Statistics, Point Sampling  | Lab 12 |              | [Lab 10](lab_10.html)                                        |
| February 16  | 7    | Holiday - NO CLASS                                                   |        |              |                                               |  
| February 18  | 7    |                                                                      | Lab 13 |              | [Lab 11](lab_11.html)                         |
| February 23  | 8    | Workflow Design and Geoprocessing Models                             | Lab 14 |              | [Project 3](project_3.md)                     |
| February 25  | 8    | Georeferencing                                                       | Lab 15 |              |                                               |
| March 2      | 9    | Advanced Topics (tbd)                                                | Lab 16 |              | Lab 14                                        |
| March 4      | 9    |                                                                      | Lab 17 |              | Lab 15                                        |
| March 9      | 10   | Modern Map Making                                                    | Lab 17 |              |                                               |  
| March 11     | 10   |                                                                      | Lab 19 |              | [Project 4]((project_4.md))                                              |
       
