# Tips for Mac Users

- [Making your home directory visible in Finder](#making-your-home-directory-visible-in-finder)
- [Installing QGIS on Mac](#installing-qgis-on-mac)
- [Installing Homebrew](#installing-homebrew)
- [Installing tree command](#installing-tree-command)

## Making your home directory visible in Finder

+ To show your home directory in macOS Finder, open Finder and press `Shift+Command+H`

+ To add it to the sidebar drag the folder icon (at the top of the window) into the sidebar. 

## Installing QGIS on Mac {style="font-size:0.6em"}

There are some bugs in recent versions of QGIS on Mac.

+ QGIS 4.0 hangs up and crashes while opening on some Macs (I think Macs with intel processors work ok, but the newer Apple Silicon based Macs do not). Here is the [link to the issue on GitHub](https://github.com/qgis/QGIS/issues/65037).  If 4.0 works on your computer, then great, problem solved. If not read on.
+ QGIS 3.4xx Is missing proj.db, and thus cannot do anything related to Raster reprojection, which renders it more or less useless.  Here is the [link to the issue on GitHub](https://github.com/qgis/QGIS/issues/65102).

It is possible that one or both of these issues will be resolved soon, but we cannot depend on that. The best solution currently is to use the older version 3.34.  Unfortunately there is no archived QGIS 3.34 macOS .dmg in the QGIS old releases archive. So, options are

+ [Easy] Use the lab computer
+ [I have not tested] Using homebrew try `brew install --cask qgis` (see [Installing Homebrew](#installing-homebrew))

## Installing Homebrew {style="font-size:0.7em"}

1. go to the [Homebrew website](https://brew.sh/)
2. Copy the command for installing Homebrew and paste into your terminal (and press enter), it should look something like
```
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
```
(This just downloads the `install.sh` file and executes it, installing Homebrew)

3. Follow the prompts, enter your password (you will not be able to see it as you enter it).

4. There may be a message about "Next steps".  You can ignore that.

## Installing tree command

In terminal `brew install tree`. (If Homebrew is not yet installed see [Installing Homebrew](#installing-homebrew).)
