---
title: "Section 09 Schedule"
format:
  html:
    theme: cyborg
    css: ../style/terminal_theme.css
    include-after-body: style/terminal_theme_include_subdir.html
---


## Class Details
Room __TBD__

__Two hours of lecture per week __  
Monday: 6:00 - 7:50  

__Three hours of lab per week __  
Wednesday: 6:00 - 8:50 


## Instructor Details
Michael Huggins  
&#9993; [mthuggin@calpoly.edu](mailto:mthuggin@calpoly.edu)  
Office Hours: Mondays 2:00 - 4:00  
Building 72-107 (Plant Conservatory)  

__TA:__ TBD

## Learning Goals
+ How to formulate and answer problems using spatial data  
+ How to create quality maps and graphics
+ Apply skills in remote sensing, GIS, and data science to solve a problem
+ Understand basic principles of GIS


## Labs
Not every lab requires you turn in your results. The [calendar](#spring-term-calendar-2026) lists due dates for the labs that need to be turned in.

## Quizzes
There will be five quizzes. For each quiz, if you get 75% of the points, you get full credit.  Beyond 75% correct will allow you to earn up to 25% of the quiz value in extra credit.

## Assignment Weight
| Assignment     | Percentage of Grade| Description  |
|---------------------------|-----|----|
| Lab exercises             | 42  |  There are 7 assignments that need to be turned in  |
| Quizzes                   | 18  |  Quizzes can happen any time! |
| [Cachuma Project](../project_cachuma.html) | 20  |  Will use skills learned throughout the quarter  |
| Final Exam                | 20  |  Oral exam, in which you will explain what you did in the Cachuma project  |  

## Grading

A: ≥ 90%  
B: ≥ 80%  
C: ≥ 70%  
D: ≥ 60%  
F: < 60%  

Note: Grading is not curved.


## Assignment Submission Policy 
Assignments  will be submitted on Canvas.  Late assignments will be penalized by 5% for every day they are late.

## Academic Integrity
All students should be familiar with and adhere to the university’s academic integrity policy, which can be found here: https://osrr.calpoly.edu/academic-integrity 

## Use of AI
AI generated text __may not be used__ for any writing.

Students can seek AI assistance for project work, but it is important to consider that AI will make you stupid ([See this study for example](https://www.researchgate.net/publication/392560878_Your_Brain_on_ChatGPT_Accumulation_of_Cognitive_Debt_when_Using_an_AI_Assistant_for_Essay_Writing_Task)) and waste your time!

  + Depending on AI prevents development of critical thinking, writing, and problem-solving skills
  + AI will often lead you down a terrible, deep rabbit hole of confusion
  + Getting quick answers without working through problems will leave gaps in foundational knowledge needed for advanced coursework
  + The struggle of working through difficult concepts is often where the most valuable learning occurs
  + AI uses heaps of electricity

That is not to say LLMs are never useful or appropriate to use, but you need to know their limitations.  I suggest reading this [critical AI literacy guide](https://rutgers.app.box.com/s/v1ywq3701cb6pvnewz5ptuhojwwppmsg/file/1640499870205) from Rutgers University.

 
## Textbook
Some assignments will ask you to read excerpts from  Essentials of Geographic Information Systems during this course. A free and online version of the textbook can be found [here](https://saylordotorg.github.io/text_essentials-of-geographic-information-systems).


## Tutorials
We will refer to a number of tutorial videos which describe QGIS processing. These will come primarily from two sources: 

[Ujaval Gandhi's QGIS Tutorials and Tips](https://www.qgistutorials.com/en/index.html)  
[QGIS Training Manual](https://docs.qgis.org/3.34/en/docs/training_manual/index.html)

There are many other helpful sources of information on GIS Software, here area couple:

[Spatial Thoughts introduction-to-qgis.html ](https://courses.spatialthoughts.com/)   
[A Gentle Introduction to GIS  gentle_gis_introduction/index.html](https://docs.qgis.org/3.40/en/docs/)



# Section 09 - Fall Term Calendar 2026

| Date         | Week | Topic                                                           | 
|--------------|-----:|-----------------------------------------------------------------|
| August 24    | 1          | Lecture: Introduction, What is GIS, Computers Reading: [On Computers](../computers.html) |
| August 26    | 1          | [Lab 1, Computers](../lab_01_computers.html)   |
| August 31    | 2          | Lecture: Basic GIS Concepts \| Scale, Coordinate systems, and Map Projections <br> Lecture: Spatial Data Models and File Formats   |
| September 2  | 2          | [Lab 2, Basics and First Map](../lab_02_first_map.html)   |
| September 7  | Labor Day  | Academic holiday – no class   |
| September 9  | 3          | Open Lab   |
| September 14 | 4          | Lecture: Data Creation, Editing, Topology Basics    |
| September 16 | 4          | [Lab 3, Vectors](../lab_03_vectors.html)   |
| September 21 | 5          | Lecture: Tables: Joins and Queries, GeoProcessing and Vector Operations   | 
| September 23 | 5          | Open Lab   | 
| September 28 | 6          | Lecture: GCS Review, GPS, plotting x/y coordinates, exporting vector data   | 
| September 30 | 6          | Lab: GPS   | 
| October 5    | 7          | Lecture: Rasters and Digital Elevation Models   | 
| October 7    | 7          | [Lab 4, DEMs](../lab_04_DEMS.html)   | 
| October 12   | 8          | Lecture: Raster Analysis: Map Algebra, Resampling, Reprojecting Rasters   | 
| October 14   | 8          | Open Lab   | 
| October 19   | 9          | Lecture: Remote Sensing and Spectral Indices   | 
| October 21   | 9          | [Lab 5, Using Multi-spectral Data](../lab_05_NAIP.html)   | 
| October 26   | 10         | Lecture: Interpolation, Zonal Statistics, and Summarizing Surfaces   | 
| October 28   | 10         | Open Lab   | 
| November 2   | 11         | Lecture: Segmentation, Normalized Difference Hotdog Index   | 
| November 4   | 11         | [Lab 6, Segmentation](../lab_06_segmentation.html)   | 
| November 9   | 12         | Open lab  | 
| November 11  | Veterans Day | Academic holiday – no class   | 
| November 16  | 13         | Lecture: Workflow Design and Geoprocessing Models   | 
| November 18  | 13         | [Lab 7, Change Detection](../lab_07_gran_chaco.html)   | 
| November 23  | Fall Break |       | 
| November 25  | Fall Break |       | 
| November 30  | 14         | Project introduction    | 
| December 2   | 14         | Project   | 
| December 7   | 15         | Lecture: Other GIS platforms   | 
| December 9   | 15         | Project   | 


       
