# Tips for Mac Users

- [Making your home directory visible in Finder](#making-your-home-directory-visible-in-finder)
- [Installing QGIS on Mac](#installing-qgis-on-mac)
- [Installing Homebrew](#installing-homebrew)
- [Installing tree command](#installing-tree-command)

## Making your home directory visible in Finder {style="font-size:0.7em"}

To jump to your home directory in macOS Finder,  

+ open Finder and press `Shift+Command+H`.
+ To add it to the sidebar drag the folder icon (at the top of the window) into the sidebar. 

To add the Path bar, which will let you see  paths to files, 

+ open Finder
+ in the dropdown menu, go to _View_ > _Show Path Bar_
Now, there should be a bar (probably at the bottom of the window) showing the path to the directory you are in.

## Installing QGIS on Mac {style="font-size:0.6em"}

1. Go to the [QGIS download page](https://www.qgis.org/download/).
2. Under macOS, download the **Long Term Release**. For class, use the LTR unless I say otherwise.
3. Open the `.dmg` file and drag **QGIS** into the `Applications` folder.
4. Open QGIS from `Applications`.

Common Mac issues:

+ If macOS blocks QGIS the first time, open **System Settings** > **Privacy & Security** and choose **Open Anyway** for QGIS. This is Gatekeeper, not a broken install.
+ QGIS 4 is newer, but some plugins may still lag behind it. The LTR is the safer choice for class.
+ Do not install QGIS with Homebrew or MacPorts for this class. Use the official `.dmg`; package-manager installs can create dependency conflicts.
+ Very old Macs may not be supported by the current installer.



## Installing Homebrew {style="font-size:0.7em"}

1. go to the [Homebrew website](https://brew.sh/)
2. Copy the command for installing Homebrew and paste into your terminal (and press enter), it should look something like
```
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
```
(This just downloads the `install.sh` file and executes it, installing Homebrew)

3. Follow the prompts, enter your password (you will not be able to see it as you enter it).

4. There may be a message about "Next steps".  You can ignore that.

## Installing tree command

In terminal `brew install tree`. (If Homebrew is not yet installed see [Installing Homebrew](#installing-homebrew).)
